services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./metrics_configs/prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      - badger
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./metrics_configs/grafana:/etc/grafana/provisioning/datasources
    networks:
      - badger
  pushgateway:
    image: prom/pushgateway
    container_name: prom-pushgateway
    ports:
      - 9091:9091
    networks:
      - badger
volumes:
  prom_data:
networks:
  badger:
    name: badger
    external: true