version: '3.7'
services:
    web_2024:
      image: meecles/badge-api-2024
      build: ./core/
      container_name: badge-api-2024
      restart: unless-stopped
      volumes:
        - ./core/templates:/root/templates
        - ./core/static:/root/static
        - ./logs:/logs
      environment:
        - MONGO_IP=mongo.badger
        - IS_DOCKER=true
        - GRAVWELL_HOST=simple-relay.badger
      ports:
        - 8080:8080
      networks:
        - badger
networks:
  badger:
    name: badger
    external: true
