version: '3.7'
services:
    web_2024:
      image: meecles/badge-api-2024
      build: .
      container_name: badge-api-2024
      restart: unless-stopped
      volumes:
        - ./templates:/root/templates
        - ./static:/root/static
      environment:
        - MONGO_IP=mongo.badger
      ports:
        - 8091:8080
      networks:
        - badger
networks:
  badger:
    name: badger
    external: true
