version: '3.7'
services:
    tasks_2024:
      image: meecles/badge-tasks-2024
      build: ./task_engine/
      container_name: badge-tasks-2024
      restart: unless-stopped
      volumes:
        - ./logs:/logs
      environment:
        - MONGO_IP=mongo.badger
        - PROMETHEUS_MULTIPROC_DIR=/root/prometheus_registry
        - PUSH_REGISTRY=pushgateway.badger:9091
        - IS_DOCKER=true
      networks:
        - badger
networks:
  badger:
    name: badger
    external: true
