version: "3.5"

networks:
  badger:
    name: badger
    external: true

services:
  gravwell:
    image: "gravwell/gravwell:latest"
    restart: always
    ports:
      - 8081:80
    volumes:
      - gravwell-etc:/opt/gravwell/etc
      - gravwell-storage:/opt/gravwell/storage
    # Don't forget to configure your volumes, so that your data persists!
    # See https://docs.gravwell.io/configuration/docker.html#configuring-persistent-storage
    # volumes:
    networks:
      - badger
    environment:
      - GRAVWELL_INGEST_SECRET=MyIngestSecret
      - GRAVWELL_INGEST_AUTH=MyIngestSecret
      - GRAVWELL_CONTROL_AUTH=MyControlSecret
      - GRAVWELL_SEARCHAGENT_AUTH=MySearchAgentAuth

  simple-relay:
    image: "gravwell/simple_relay:latest"
    restart: always
    depends_on:
      - gravwell
    networks:
      - badger
    environment:
      - GRAVWELL_CLEARTEXT_TARGETS=gravwell
      - GRAVWELL_INGEST_SECRET=MyIngestSecret

  netflow-capture:
    image: "gravwell/netflow_capture:latest"
    restart: always
    depends_on:
      - gravwell
    networks:
      - badger
    environment:
      - GRAVWELL_CLEARTEXT_TARGETS=gravwell
      - GRAVWELL_INGEST_SECRET=MyIngestSecret
volumes:
  gravwell-etc:
  gravwell-storage: