{
 "title": "Test Dasboard",
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Players in Houses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "apiserver_houses_occupied_players{houseowner=\"True\"}",
     "legendFormat": "In House"
    },
    {
     "expr": "apiserver_houses_occupied_players{houseowner=\"False\"}",
     "legendFormat": "Robbing"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_http_requests_total[1m])) * 60 # Total http requests per minute",
     "legendFormat": "Per Minute"
    }
   ]
  },
  {
   "title": "Houses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "apiserver_houses_number{abandoned=\"False\"}",
     "legendFormat": "Houses"
    },
    {
     "expr": "apiserver_houses_number{abandoned=\"True\"}",
     "legendFormat": "Abandoned"
    }
   ]
  },
  {
   "title": "Players",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "apiserver_players_number{active=\"True\"}",
     "legendFormat": "Active Players"
    }
   ]
  }
 ]
}